version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "LabelTriggerStack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-15hjk8wmmemlu"
s3_prefix = "LabelTriggerStack"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
